# Generated by Django 5.1.7 on 2025-04-29 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_configuration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
